---
title: "day4"
format: html
---

what I am doing is alingning is aligning all reads not just again chr1 but again all
```{bash}
# 1. Map reads to Reference
minimap2 -ax map-ont reference_snpeff_S288C.fna ERR1539006.fastq | \
  samtools sort -o snpeff_reference_genome_aligned.bam

# 2. Index the BAM (creates .bam.bai)
samtools index data_Ankur/snpeff_reference_genome_aligned.bam
```

```{r}
file <- Biostrings::readDNAStringSet("S288C_UCSC.fna")
names(file) <- stringr::str_remove(names(file),"chr")
names(file)
names(file) <- stringr::str_replace(names(file),"M", "Mito")
Biostrings::writeXStringSet(file, "reference_snpeff_S288C.fna")
```


```{bash}
medaka_variant -i ERR1539006.fastq -r reference_snpeff_S288C.fna -t 8
```

```{r}
# 1. Uncompress and Read the raw NCBI file as simple text
con <- "GCF_000146045.2_R64_genomic.test.fna"
ygen <- readLines(con)

close(con)  # <-- this is for closing the connection to the gz file, saves on resources. 



# 2. Define the new UCSC-style headers (chrI through chrXVI + chrM)
new_headers <- c(paste0(">chr", as.roman(1:16)), ">chrM")

# 3. Find and Replace
header_lines <- grep(">", ygen)
#Look at the header for chromosome 1
header_lines[1]

# Safety Check: Yeast has 16 nuclear chromosomes + 1 mitochondrial
if(length(header_lines) == 17) {
  ygen[header_lines] <- new_headers
  writeLines(ygen, "S288C_UCSC.fna")
  message("SUCCESS: Reference renamed to UCSC standards.")
} else {
  stop("Error: Chromosome count mismatch! Check your input file.")
}
```


```{bash}
#1 Create the gene only GFF
awk 'BEGIN{FS=OFS="\t"} $0 ~ /^#/ || $3=="gene"' \
S288C_reference.gff > S288C_genes.gff

#2 Check for overlaps between Variants (A) and Genes (B)
# Ensure variant_env is active
# We use -a (the variant file) and -b (the gene feature file)
bedtools intersect \
  -a medaka/medaka.vcf \
  -b S288C_genes.gff \
  -header > variants_in_genes.vcf
```

```{bash}
medaka_variant -i data_ankur/ERR1539006.fastq -r data_ankur/S288C_UCSC.fna -t 8
```

```{bash}
# Use the S. cerevisiae R64-1-1.99 database
snpeff R64-1-1.99 data/data_ankur/medaka/medaka.vcf > data/data_ankur/medaka/snpeff_medaka.annotateds.vcf
```

```{bash}
# 1. Align Assembly to Reference
minimap2 -cx asm5 data/data_ankur/reference_snpeff_S288C.fna data/data_ankur/5scaff2medaka_consensus.fasta > data/ankur_asm_to_ref.paf

# 2. Convert PAF map into a .chain dictionary
# conda install paf2chain
paf2chain --input data/ankur_asm_to_ref.paf > data/ankur_isolate_to_ref.chain
```

```{bash}
CrossMap vcf data/ankur_isolate_to_ref.chain data/data_ankur/medaka/medaka.vcf data/data_ankur/5scaff2medaka_consensus.fasta data/ankur_isolate_centric.vcf
```

```{r}
library("tidyverse")
library("Gviz")
library("GenomicFeatures")
library("rtracklayer")
library("Biostrings")
library("GO.db")
library("AnnotationDbi")
library("ggVennDiagram")
```
```{r}
library(Gviz)
library(rtracklayer)
library(GenomicRanges)
library(GenomicFeatures)
library(VariantAnnotation)

options(ucscChromosomeNames=FALSE)

# 1. Load Isolate Annotations (Day 1) and Lifted VCF (Today)
isolate_txdb <- makeTxDbFromGFF("data/data_ankur/ankur_Saccharomyces_cerevisiae.gff3")
gr_lifted <- readVcf("data/Ankur/ankur_isolate_centric.vcf")
gr_vcf <- rowRanges(gr_lifted)

# 2. Make names consistent
seqlevels(gr_vcf) <- sub("contig", "scaffold", seqlevels(gr_vcf))
chrom <- "scaffold_322"

# 2. Create Tracks
it_track <- GeneRegionTrack(isolate_txdb,
                            name = "Isolate Genes",
                            chromosome = chrom)

iv_track <- AnnotationTrack(gr_vcf,
                            name = "Ref-based SNPs",
                            fill = "red",
                            chromosome = chrom)
# 3. Plot the Synthesis
plotTracks(list(GenomeAxisTrack(), it_track, iv_track),
           chromosome = chrom,
           from = 1, to = 10000,
           main = "The Isolate Map: Integrated Structure & Function")
```


